apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dukes-liberty
  labels:
    app: dukes-liberty
    visualize: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dukes-liberty
  template:
    metadata:
      labels:
        app: dukes-liberty
        version: "v1"
        vusualize: "true"
    spec:
      containers:
      - name: dukes-liberty
        image: ivargrimstad/dukes-liberty:liberty-micro
        env:
        - name: place
          value: Passion
        ports:
        - name: http
          containerPort: 9080